password_enhancements.policy.*:
  type: config_entity
  label: 'Password policy'
  mapping:
    expireDays:
      type: integer
      label: 'Expire days'
    id:
      type: string
      label: 'ID'
    name:
      type: label
      label: 'Name'
    minimumRequiredConstraints:
      type: int
      label: 'Minimum required constraints'
    priority:
      type: string
      label: 'Priority'
    role:
      type: string
      label: 'User role'
