password_enhancements.constraint.*:
  type: config_entity
  label: 'Password constraint'
  mapping:
    descriptionSingular:
      type: text
      label: 'Description (singular)'
    descriptionPlural:
      type: text
      label: 'Description (plural)'
    policy:
      type: string
      label: 'Policy ID'
    required:
      type: boolean
      label: 'Required'
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        type: string
    type:
      type: string
      label: 'Type'
